#!/usr/bin/env python3
"""
tools/download_tiles.py — Pre-download OSM tiles for offline map use.

Downloads OpenStreetMap tiles for a given bounding box and zoom range,
storing them in an SQLite database compatible with tkintermapview.

Usage:
    python3 tools/download_tiles.py [OPTIONS]

Examples:
    # Download tiles for Lago di Garda, zoom 8-14:
    python3 tools/download_tiles.py \\
        --lat-min 45.4 --lat-max 45.9 \\
        --lon-min 10.4 --lon-max 10.9 \\
        --zoom-min 8 --zoom-max 14 \\
        --output /tmp/map_tiles.db

    # Dry run (show tile count only, no download):
    python3 tools/download_tiles.py --dry-run \\
        --lat-min 45.4 --lat-max 45.9 \\
        --lon-min 10.4 --lon-max 10.9 \\
        --zoom-min 8 --zoom-max 14

Notes:
    - OSM tile usage policy: max 2 req/s, identify with a User-Agent.
      See https://operations.osmfoundation.org/policies/tiles/
    - For large areas use a local tile mirror or Maptiler instead.
    - The output .db can also be generated by tkintermapview's built-in
      offline_loading.load_tiles_from_zip().
"""

import argparse
import logging
import math
import os
import sqlite3
import sys
import time

try:
    import requests
    REQUESTS_OK = True
except ImportError:
    REQUESTS_OK = False

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s  %(levelname)-7s  %(message)s",
                    datefmt="%H:%M:%S")
logger = logging.getLogger("download_tiles")

# OSM tile URL template
_TILE_URL = "https://tile.openstreetmap.org/{z}/{x}/{y}.png"

# tkintermapview SQLite schema
_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS tiles (
    zoom_level  INTEGER NOT NULL,
    tile_column INTEGER NOT NULL,
    tile_row    INTEGER NOT NULL,
    tile_data   BLOB    NOT NULL,
    PRIMARY KEY (zoom_level, tile_column, tile_row)
)
"""


def _lat_to_tile_y(lat: float, zoom: int) -> int:
    lat_r = math.radians(lat)
    n = 2 ** zoom
    return int((1.0 - math.log(math.tan(lat_r) + 1.0 / math.cos(lat_r)) / math.pi)
               / 2.0 * n)


def _lon_to_tile_x(lon: float, zoom: int) -> int:
    return int((lon + 180.0) / 360.0 * (2 ** zoom))


def _tile_bounds(lat_min, lat_max, lon_min, lon_max, zoom):
    """Return (x_min, x_max, y_min, y_max) tile indices for bounding box."""
    x_min = _lon_to_tile_x(lon_min, zoom)
    x_max = _lon_to_tile_x(lon_max, zoom)
    # Note: lat_max → smaller y_tile (tiles increase southward)
    y_min = _lat_to_tile_y(lat_max, zoom)
    y_max = _lat_to_tile_y(lat_min, zoom)
    return x_min, x_max, y_min, y_max


def _count_tiles(lat_min, lat_max, lon_min, lon_max, zoom_min, zoom_max):
    total = 0
    for z in range(zoom_min, zoom_max + 1):
        x0, x1, y0, y1 = _tile_bounds(lat_min, lat_max, lon_min, lon_max, z)
        total += (x1 - x0 + 1) * (y1 - y0 + 1)
    return total


def download_tiles(lat_min: float, lat_max: float,
                   lon_min: float, lon_max: float,
                   zoom_min: int, zoom_max: int,
                   output: str,
                   tile_url: str = _TILE_URL,
                   delay: float = 0.5,
                   dry_run: bool = False) -> int:
    """
    Download tiles and store in SQLite.

    Returns number of tiles downloaded (or that would be downloaded).
    """
    total = _count_tiles(lat_min, lat_max, lon_min, lon_max, zoom_min, zoom_max)
    logger.info("Tiles to download: %d", total)

    if dry_run:
        logger.info("Dry run — no files written")
        return total

    if not REQUESTS_OK:
        logger.error("requests library not installed. Run: pip install requests")
        return 0

    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    conn = sqlite3.connect(output)
    conn.execute(_CREATE_TABLE)
    conn.commit()

    session = requests.Session()
    session.headers["User-Agent"] = "Mesh-pi/1.0 tile downloader (offline use)"

    downloaded = 0
    skipped    = 0
    errors     = 0

    for z in range(zoom_min, zoom_max + 1):
        x0, x1, y0, y1 = _tile_bounds(lat_min, lat_max, lon_min, lon_max, z)
        for x in range(x0, x1 + 1):
            for y in range(y0, y1 + 1):
                # Check if already cached
                row = conn.execute(
                    "SELECT 1 FROM tiles WHERE zoom_level=? AND tile_column=? AND tile_row=?",
                    (z, x, y)
                ).fetchone()
                if row:
                    skipped += 1
                    continue

                url = tile_url.format(z=z, x=x, y=y)
                try:
                    resp = session.get(url, timeout=10)
                    resp.raise_for_status()
                    conn.execute(
                        "INSERT OR REPLACE INTO tiles VALUES (?,?,?,?)",
                        (z, x, y, resp.content)
                    )
                    conn.commit()
                    downloaded += 1
                    if downloaded % 50 == 0:
                        pct = (downloaded + skipped) / total * 100
                        logger.info("Progress: %d/%d (%.0f%%)  errors: %d",
                                    downloaded + skipped, total, pct, errors)
                    time.sleep(delay)
                except Exception as exc:
                    logger.warning("Failed z=%d x=%d y=%d: %s", z, x, y, exc)
                    errors += 1

    conn.close()
    logger.info("Done. Downloaded: %d  Skipped (cached): %d  Errors: %d",
                downloaded, skipped, errors)
    logger.info("Saved to: %s  (%.1f MB)",
                output, os.path.getsize(output) / 1024 / 1024)
    return downloaded


def main():
    parser = argparse.ArgumentParser(
        description="Pre-download OSM map tiles for offline use with Mesh-pi.")
    parser.add_argument("--lat-min",  type=float, default=45.4,
                        help="South latitude boundary (default: 45.4)")
    parser.add_argument("--lat-max",  type=float, default=45.9,
                        help="North latitude boundary (default: 45.9)")
    parser.add_argument("--lon-min",  type=float, default=10.4,
                        help="West longitude boundary (default: 10.4)")
    parser.add_argument("--lon-max",  type=float, default=10.9,
                        help="East longitude boundary (default: 10.9)")
    parser.add_argument("--zoom-min", type=int, default=8,
                        help="Minimum zoom level to download (default: 8)")
    parser.add_argument("--zoom-max", type=int, default=14,
                        help="Maximum zoom level to download (default: 14)")
    parser.add_argument("--output",   default="/tmp/map_tiles.db",
                        help="Output SQLite database path (default: /tmp/map_tiles.db)")
    parser.add_argument("--tile-url", default=_TILE_URL,
                        help="Tile URL template with {z}/{x}/{y} placeholders")
    parser.add_argument("--delay",    type=float, default=0.5,
                        help="Delay between requests in seconds (default: 0.5)")
    parser.add_argument("--dry-run",  action="store_true",
                        help="Count tiles without downloading")
    args = parser.parse_args()

    if args.lat_min >= args.lat_max:
        parser.error("--lat-min must be less than --lat-max")
    if args.lon_min >= args.lon_max:
        parser.error("--lon-min must be less than --lon-max")
    if args.zoom_min > args.zoom_max:
        parser.error("--zoom-min must be <= --zoom-max")
    if args.zoom_max > 17:
        logger.warning("zoom > 17 can produce millions of tiles — be careful")

    total = download_tiles(
        lat_min=args.lat_min, lat_max=args.lat_max,
        lon_min=args.lon_min, lon_max=args.lon_max,
        zoom_min=args.zoom_min, zoom_max=args.zoom_max,
        output=args.output,
        tile_url=args.tile_url,
        delay=args.delay,
        dry_run=args.dry_run,
    )
    sys.exit(0 if total >= 0 else 1)


if __name__ == "__main__":
    main()
